version: '3.7'

services:
  postgresql:
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASS}
        POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]
    build:
        context: ./docker/db
    volumes:
        - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "${POSTGRES_PORT}:5432"
    networks:
        - everlasting-nt

  minio_latest:
    container_name: everlasting-minio
    image: minio/minio:latest
    ports:
      - "${MINIO_SVC_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - "./docker/minio:/data"
    networks:
      - everlasting-nt
    environment:
      - MINIO_ROOT_USER=${MINIO_CONSOLE_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_CONSOLE_PASSWORD}
    command: server /data --console-address ":9001"

  redis:
    container_name: everlasting-redis
    image: redis:latest
    command: >
          --requirepass ${REDIS_PASS}
    volumes:
      - './docker/redis:/data'
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - TZ=Asia/Jakarta
    networks:
        - everlasting-nt

  rabbitmq:
    container_name: 'everlasting-rabbitmq'
    build: 
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_ADMINPORT}:15672
    environment:
      - TZ=Asia/Jakarta
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - everlasting-nt

networks:
  everlasting-nt:
      driver: bridge
