sonar.projectKey=the-hcp-project_aicare-klondike_AYzHoPH037Yp3kPKTNMQ
sonar.qualitygate.wait=true
sonar.projectName= aicare - AiCare Klondike
sonar.exclusions=**/mocks/*.go, *.yml, *.yaml, *.json, **/Dockerfile, LICENSE, README.md, wait-for-it.sh, **/*_test.go, docs/, docker/

sonar.sources=./src/domain
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
