// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user using provided credentials.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Handle user login",
                "parameters": [
                    {
                        "description": "User credentials for login",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.Credential"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.SuccessfulLoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/example.InvalidCredentialResponse"
                        }
                    }
                }
            }
        },
        "/reset-password/redeem-token": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reset Password"
                ],
                "summary": "Redeem token from verification code",
                "parameters": [
                    {
                        "description": "resetpassword.RedeemTokenRequest",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resetpassword.RedeemTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.SuccessfulRedeemToken"
                        }
                    }
                }
            }
        },
        "/reset-password/request": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reset Password"
                ],
                "summary": "Request reset password email",
                "parameters": [
                    {
                        "description": "resetpassword.ResetPasswordRequest",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resetpassword.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.SuccessfulResetPassword"
                        }
                    }
                }
            }
        },
        "/reset-password/submit": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reset Password"
                ],
                "summary": "Submit new password",
                "parameters": [
                    {
                        "description": "resetpassword.SubmitPasswordRequest",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/resetpassword.SubmitPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.SuccessfulRedeemToken"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get list of user. Paginated",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by name.",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "superadmin",
                            "admin"
                        ],
                        "type": "string",
                        "description": "Filter by user role",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "active",
                            "inactive"
                        ],
                        "type": "string",
                        "description": "Filter by user status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "created_at",
                            "name",
                            "last_transaction"
                        ],
                        "type": "string",
                        "description": "Sort by",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sorting order",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Current page, default is 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Displayed data per page, default is 20",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.UsersResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "### Param (JSON Body)\n- name (string) : User Full Name\n- email (string) : User email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create new user account",
                "parameters": [
                    {
                        "description": "User",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.UserResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.UserResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "### Param (JSON Body)\n- name (string) : User Full Name\n- email (string) : User email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.UserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "example.InvalidCredentialResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "bad_request"
                        },
                        "message": {
                            "type": "string",
                            "example": "invalid credential"
                        }
                    }
                }
            }
        },
        "example.SuccessfulLoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "access_token": {
                            "type": "string",
                            "example": "your_access_token"
                        },
                        "refresh_token": {
                            "type": "string",
                            "example": "your_refresh_token"
                        }
                    }
                },
                "meta": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "ok"
                        },
                        "message": {
                            "type": "string",
                            "example": "Ok"
                        }
                    }
                }
            }
        },
        "example.SuccessfulRedeemToken": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQzNjI3MTEsImlkIjoiN2IyYWE2MTEtMmViMS00NDI0LWJjNWEtYjg2N2I3MTBmYWQ3Iiwic3ViamVjdCI6InJlc2V0X3Bhc3N3b3JkIn0.G_Uofrg80H4WwoRZzjUH6-UbT_4otd8VwMqNOZOyB5w"
                },
                "meta": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "ok"
                        },
                        "message": {
                            "type": "string",
                            "example": "Ok"
                        }
                    }
                }
            }
        },
        "example.SuccessfulResetPassword": {
            "type": "object",
            "properties": {
                "meta": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "ok"
                        },
                        "message": {
                            "type": "string",
                            "example": "Ok"
                        }
                    }
                }
            }
        },
        "example.UserItem": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "8f364610-6f12-4bed-b7d1-7ea1892803c7"
                },
                "balance": {
                    "type": "number",
                    "example": 240000
                },
                "created_at": {
                    "type": "string"
                },
                "last_transaction": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "markonah"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "example.UserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/example.UserItem"
                },
                "meta": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "ok"
                        },
                        "message": {
                            "type": "string",
                            "example": "Ok"
                        }
                    }
                }
            }
        },
        "example.UsersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example.UserItem"
                    }
                },
                "meta": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "ok"
                        },
                        "detail": {
                            "type": "object",
                            "properties": {
                                "pagination": {
                                    "type": "object",
                                    "properties": {
                                        "current_page": {
                                            "type": "integer",
                                            "example": 1
                                        },
                                        "max_page": {
                                            "type": "integer",
                                            "example": 2
                                        },
                                        "total_data": {
                                            "type": "integer",
                                            "example": 10
                                        }
                                    }
                                }
                            }
                        },
                        "message": {
                            "type": "string",
                            "example": "Ok"
                        }
                    }
                }
            }
        },
        "resetpassword.RedeemTokenRequest": {
            "type": "object",
            "required": [
                "verification_code"
            ],
            "properties": {
                "verification_code": {
                    "type": "string",
                    "example": "my_verification_code"
                }
            }
        },
        "resetpassword.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "xxx@yyy.zzz"
                }
            }
        },
        "resetpassword.SubmitPasswordRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "1234qweR!"
                },
                "password_confirm": {
                    "type": "string",
                    "example": "1234qweR!"
                }
            }
        },
        "user.Credential": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@klondike.id"
                },
                "password": {
                    "type": "string",
                    "example": "1234qweR!"
                }
            }
        },
        "user.UserInput": {
            "type": "object",
            "required": [
                "email",
                "name",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "user-assistant"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
