// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	renderer "everlasting/src/domain/sharedkernel/renderer"

	mock "github.com/stretchr/testify/mock"
)

// HTMLRenderer is an autogenerated mock type for the HTMLRenderer type
type HTMLRenderer struct {
	mock.Mock
}

// Render provides a mock function with given fields: template, values
func (_m *HTMLRenderer) Render(template renderer.Template, values map[string]interface{}) (string, error) {
	ret := _m.Called(template, values)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(renderer.Template, map[string]interface{}) (string, error)); ok {
		return rf(template, values)
	}
	if rf, ok := ret.Get(0).(func(renderer.Template, map[string]interface{}) string); ok {
		r0 = rf(template, values)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(renderer.Template, map[string]interface{}) error); ok {
		r1 = rf(template, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHTMLRenderer creates a new instance of HTMLRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTMLRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTMLRenderer {
	mock := &HTMLRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
