// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KeyGenerator is an autogenerated mock type for the KeyGenerator type
type KeyGenerator struct {
	mock.Mock
}

// DecryptBase64 provides a mock function with given fields: base64
func (_m *KeyGenerator) DecryptBase64(base64 string) (string, error) {
	ret := _m.Called(base64)

	if len(ret) == 0 {
		panic("no return value specified for DecryptBase64")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(base64)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(base64)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(base64)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Generate provides a mock function with given fields: identifier, key
func (_m *KeyGenerator) Generate(identifier string, key string) (string, error) {
	ret := _m.Called(identifier, key)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(identifier, key)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(identifier, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(identifier, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateBase64 provides a mock function with given fields: message
func (_m *KeyGenerator) GenerateBase64(message string) (string, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBase64")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Parse provides a mock function with given fields: message, key
func (_m *KeyGenerator) Parse(message string, key string) (string, error) {
	ret := _m.Called(message, key)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(message, key)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(message, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(message, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKeyGenerator creates a new instance of KeyGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyGenerator {
	mock := &KeyGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
