// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	messagebroker "everlasting/src/domain/sharedkernel/messagebroker"

	mock "github.com/stretchr/testify/mock"
)

// MessageBroker is an autogenerated mock type for the MessageBroker type
type MessageBroker struct {
	mock.Mock
}

// Produce provides a mock function with given fields: ctx, task, payload
func (_m *MessageBroker) Produce(ctx context.Context, task messagebroker.TaskName, payload interface{}) error {
	ret := _m.Called(ctx, task, payload)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, messagebroker.TaskName, interface{}) error); ok {
		r0 = rf(ctx, task, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageBroker creates a new instance of MessageBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageBroker {
	mock := &MessageBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
