// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	smtp "everlasting/src/domain/sharedkernel/smtp"

	mock "github.com/stretchr/testify/mock"
)

// SMTP is an autogenerated mock type for the SMTP type
type SMTP struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, payload
func (_m *SMTP) Send(ctx context.Context, payload smtp.Payload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, smtp.Payload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSMTP creates a new instance of SMTP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSMTP(t interface {
	mock.TestingT
	Cleanup(func())
}) *SMTP {
	mock := &SMTP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
