// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	identity "everlasting/src/domain/sharedkernel/identity"

	mock "github.com/stretchr/testify/mock"

	user "everlasting/src/domain/user"
)

// TokenRepository is an autogenerated mock type for the TokenRepository type
type TokenRepository struct {
	mock.Mock
}

// Generate provides a mock function with given fields: ctx, subject, identifier, option
func (_m *TokenRepository) Generate(ctx context.Context, subject user.TokenSubject, identifier identity.ID, option user.TokenOption) (user.Token, error) {
	ret := _m.Called(ctx, subject, identifier, option)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 user.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.TokenSubject, identity.ID, user.TokenOption) (user.Token, error)); ok {
		return rf(ctx, subject, identifier, option)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.TokenSubject, identity.ID, user.TokenOption) user.Token); ok {
		r0 = rf(ctx, subject, identifier, option)
	} else {
		r0 = ret.Get(0).(user.Token)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.TokenSubject, identity.ID, user.TokenOption) error); ok {
		r1 = rf(ctx, subject, identifier, option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: ctx, token
func (_m *TokenRepository) Revoke(ctx context.Context, token user.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Verify provides a mock function with given fields: ctx, token
func (_m *TokenRepository) Verify(ctx context.Context, token user.Token) (identity.ID, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 identity.ID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.Token) (identity.ID, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.Token) identity.ID); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(identity.ID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.Token) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenRepository creates a new instance of TokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenRepository {
	mock := &TokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
