// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	identity "everlasting/src/domain/sharedkernel/identity"

	mock "github.com/stretchr/testify/mock"

	transaction "everlasting/src/domain/transaction"

	wallet "everlasting/src/domain/wallet"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, trx
func (_m *TransactionRepository) Create(ctx context.Context, trx *transaction.Transaction) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, trx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) (*transaction.Transaction, error)); ok {
		return rf(ctx, trx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) *transaction.Transaction); ok {
		r0 = rf(ctx, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *transaction.Transaction) error); ok {
		r1 = rf(ctx, trx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByQuery provides a mock function with given fields: ctx, walletID, query
func (_m *TransactionRepository) GetByQuery(ctx context.Context, walletID wallet.WalletID, query *transaction.Query) (*transaction.Transactions, error) {
	ret := _m.Called(ctx, walletID, query)

	if len(ret) == 0 {
		panic("no return value specified for GetByQuery")
	}

	var r0 *transaction.Transactions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, wallet.WalletID, *transaction.Query) (*transaction.Transactions, error)); ok {
		return rf(ctx, walletID, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, wallet.WalletID, *transaction.Query) *transaction.Transactions); ok {
		r0 = rf(ctx, walletID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transactions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, wallet.WalletID, *transaction.Query) error); ok {
		r1 = rf(ctx, walletID, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneByID provides a mock function with given fields: ctx, id
func (_m *TransactionRepository) GetOneByID(ctx context.Context, id identity.ID) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOneByID")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identity.ID) (*transaction.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identity.ID) *transaction.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identity.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneByReference provides a mock function with given fields: ctx, refType, refID
func (_m *TransactionRepository) GetOneByReference(ctx context.Context, refType transaction.TransactionRefType, refID string) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, refType, refID)

	if len(ret) == 0 {
		panic("no return value specified for GetOneByReference")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transaction.TransactionRefType, string) (*transaction.Transaction, error)); ok {
		return rf(ctx, refType, refID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transaction.TransactionRefType, string) *transaction.Transaction); ok {
		r0 = rf(ctx, refType, refID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, transaction.TransactionRefType, string) error); ok {
		r1 = rf(ctx, refType, refID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, trx
func (_m *TransactionRepository) Update(ctx context.Context, trx *transaction.Transaction) (*transaction.Transaction, error) {
	ret := _m.Called(ctx, trx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) (*transaction.Transaction, error)); ok {
		return rf(ctx, trx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) *transaction.Transaction); ok {
		r0 = rf(ctx, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *transaction.Transaction) error); ok {
		r1 = rf(ctx, trx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
